[tool.poetry]
name = "distill-to-detect"
version = "0.1.0"
description = ""
authors = ["moshebeutel <moshebeutel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ftfy = "^6.2.0"
regex = "^2024.7.24"
tqdm = "^4.66.4"
clip = {git = "https://github.com/openai/CLIP.git"}
torch = "^2.4.0"
torchvision = "^0.19.0"
packaging = "^24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
